### ISSUE TITLE
what is the used for --fixbn argument?

### ISSUE THREAD

**Issue by HashmatShadab** [VITA-Group/Adversarial-Contrastive-Learning#20]
parser.add_argument('--fixmode', default='f1', type=str,
                    help='f1: fix nothing, f2: fix previous 3 stages, f3: fix all except fc')
parser.add_argument('--fixbn', action='store_true',
                    help='if specified, fix bn for the layers been fixed')

Can you please explain what is the purpose of these arguments?

**Comment by geekJZY** [comment]
The fixmode and fixbn are for evaluating the linear probing performance (Table 5 in the ACL paper). Specifically, we only use "--fixmode f3 --fixbn" for Table5. Otherwise, we leave it to be the default value.
