### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by lisun97** [VITA-Group/Adversarial-Contrastive-Learning#3]
Hi,

Thanks for releasing the code. I notice that this repo comes with some checkpoints (e.g. ACL_DS: https://drive.google.com/file/d/1d5gZgqMpXl0-RiWH6sUcBvZZXJc2OrRF/view) But I am not sure which dataset are they trained on. Is it CIFAR-10 or CIFAR-100? If you can provide pre-trained checkpoints on both dataset that would be great. Thanks!

**Comment by geekJZY** [comment]
Thanks for your interest in our work. ACL_DS is for CIFAR10. I also added the pre-trained model for cifar100.
